# Generated by Django 6.0 on 2025-12-10 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultysubjectallocation',
            name='hours_per_week',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='facultysubjectallocation',
            unique_together={('faculty', 'subject')},
        ),
    ]
