# Generated by Django 4.1.7 on 2023-04-12 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_add_hours_per_week_field'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='facultysubjectallocation',
            unique_together=set(),
        ),
    ]
